SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
--select [DBO].[ConvertDtYMD]('15-jan-2013')
CREATE FUNCTION [dbo].[ConvertDtYMD] (@date AS datetime)  
RETURNS VARCHAR (12)   
AS BEGIN

--DECLARE  @DATE AS DATETIME; SET @DATE = '02-NOV-2011'

DECLARE  @DATEVARCHAR AS VARCHAR(12)
		,@DATE_YYYY_MM_DD as varchar(12)

SELECT	 @DATEVARCHAR = CONVERT(VARCHAR,@DATE,101)
		,@DATE_YYYY_MM_DD = substring(@DATEVARCHAR,7,4) + substring(@DATEVARCHAR,1,2) + substring(@DATEVARCHAR,4,2)

return @DATE_YYYY_MM_DD
END
GO
