SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[USP_DELETEPNRINFO]
@QueuePNRHistoryKey INT
AS
	UPDATE QUEUEPNRHISTORY 
	SET ACTIVE = 0 
	WHERE QueuePNRHistoryKey = @QueuePNRHistoryKey
	
GO
