SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[AIRPORTLOOKUP_INVALID]
(  
--DECLARE
	@PREFIXTEXT   NVARCHAR(500)
)AS /* 
SET @PREFIXTEXT = 'DFW,SFO'
-- */
	DECLARE @INVALIDAIRPORTCODE VARCHAR(8000) 
	SET		@INVALIDAIRPORTCODE = ''

	--select string from UFN_CSVSPLITSTRING(@PREFIXTEXT)  where STRING NOT IN (SELECT AIRPORTCODE FROM AIRPORTLOOKUP) and STRING <> ''

	SELECT	@INVALIDAIRPORTCODE = COALESCE(@INVALIDAIRPORTCODE + ', ', '') + STRING 
	FROM	UFN_CSVSPLITSTRING(@PREFIXTEXT) 
	WHERE	STRING <> '' AND STRING NOT IN (SELECT AIRPORTCODE FROM AIRPORTLOOKUP)

	--SELECT	InvalidAiportCode = @INVALIDAIRPORTCODE 

	IF LEN(@INVALIDAIRPORTCODE) > 0 
	BEGIN
		SET @INVALIDAIRPORTCODE = SUBSTRING(@INVALIDAIRPORTCODE, 2, LEN(@INVALIDAIRPORTCODE) - 1)
		SELECT	'Invalid Airport Code (' + @INVALIDAIRPORTCODE + ')' InvalidAiportCode
	END
	ELSE
		SELECT	'Valid' InvalidAiportCode
GO
