SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[USP_BulkInsertAirSegments]
	@airSegments TVP_AirSegment READONLY
AS
BEGIN
	INSERT INTO AirSegments (airSegmentKey,
	airResponseKey,
	airLegNumber,
	airSegmentMarketingAirlineCode,
	airSegmentOperatingAirlineCode,
	airSegmentFlightNumber,
	airSegmentDuration,
	airSegmentEquipment,
	airSegmentMiles,
	airSegmentDepartureDate,
	airSegmentArrivalDate,
	airSegmentDepartureAirport,
	airSegmentArrivalAirport,
	airSegmentResBookDesigCode,
	airSegmentDepartureOffset,
	airSegmentArrivalOffset,
	airSegmentSeatRemaining,
	airSegmentMarriageGrp,
	airFareBasisCode,
	airFareReferenceKey,	
	airSegmentOperatingFlightNumber,	
	airsegmentCabin,
	segmentOrder,
	amadeusSNDIndicator,
	airSegmentOperatingAirlineCompanyShortName,
	airSegmentBrandName,
	airSegmentBrandID,
	airSegmentBaggage,
	airSegmentMealCode,
	ProgramCode,
	isReturnFare,
	airsegmentPricingKey,
	airsegmentFareCategory,
	airSegmentStops)
	SELECT airSegmentKey,
	airResponseKey,
	airLegNumber,
	airSegmentMarketingAirlineCode,
	airSegmentOperatingAirlineCode,
	airSegmentFlightNumber,
	airSegmentDuration,
	airSegmentEquipment,
	airSegmentMiles,
	airSegmentDepartureDate,
	airSegmentArrivalDate,
	airSegmentDepartureAirport,
	airSegmentArrivalAirport,
	airSegmentResBookDesigCode,
	airSegmentDepartureOffset,
	airSegmentArrivalOffset,
	airSegmentSeatRemaining,
	airSegmentMarriageGrp,
	airFareBasisCode,
	airFareReferenceKey,	
	airSegmentOperatingFlightNumber,	
	airsegmentCabin,
	segmentOrder,
	amadeusSNDIndicator,
	airSegmentOperatingAirlineCompanyShortName,
	airSegmentBrandName,
	airSegmentBrandID,
	airSegmentBaggage,
	airSegmentMealCode,
	ProgramCode,
	isReturnFare,
	airsegmentPricingKey,
	airsegmentFareCategory,
	airSegmentStops
	FROM @airSegments
END
GO
