CREATE TYPE [dbo].[TVP_AirSegment] AS TABLE
(
[airSegmentKey] [uniqueidentifier] NOT NULL,
[airResponseKey] [uniqueidentifier] NOT NULL,
[airLegNumber] [int] NOT NULL,
[airSegmentMarketingAirlineCode] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airSegmentOperatingAirlineCode] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airSegmentFlightNumber] [int] NULL,
[airSegmentDuration] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airSegmentEquipment] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airSegmentMiles] [int] NULL,
[airSegmentDepartureDate] [datetime] NULL,
[airSegmentArrivalDate] [datetime] NULL,
[airSegmentDepartureAirport] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airSegmentArrivalAirport] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airSegmentResBookDesigCode] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airSegmentDepartureOffset] [float] NULL,
[airSegmentArrivalOffset] [float] NULL,
[airSegmentSeatRemaining] [int] NULL,
[airSegmentMarriageGrp] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airFareBasisCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airFareReferenceKey] [varchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airSegmentOperatingFlightNumber] [int] NULL,
[airsegmentCabin] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[segmentOrder] [int] NULL,
[amadeusSNDIndicator] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airSegmentOperatingAirlineCompanyShortName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airSegmentBrandName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airSegmentBrandID] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airSegmentBaggage] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airSegmentMealCode] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProgramCode] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[isReturnFare] [bit] NULL,
[airsegmentPricingKey] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airsegmentFareCategory] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airSegmentStops] [int] NULL
)
GO
