CREATE TABLE [dbo].[M_AirResponse]
(
[airResponseKey] [uniqueidentifier] NULL,
[airSubRequestKey] [int] NULL,
[airPriceBase] [float] NULL,
[airPriceTax] [float] NULL,
[gdsSourceKey] [int] NULL,
[refundable] [bit] NULL,
[airClass] [varbinary] (50) NULL,
[priceClassCommentsSuperSaver] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[priceClassCommentsEconSaver] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[priceClassCommentsFirstFlex] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[priceClassCommentsCorporate] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[priceClassCommentsEconFlex] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[priceClassCommentsEconUpgrade] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airSuperSaverPrice] [float] NULL,
[airEconSaverPrice] [float] NULL,
[airFirstFlexPrice] [float] NULL,
[airCorporatePrice] [float] NULL,
[airEconFlexPrice] [float] NULL,
[airEconUpgradePrice] [float] NULL,
[airClassSuperSaver] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airClassEconSaver] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airClassFirstFlex] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airClassCorporate] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airClassEconFlex] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airClassEconUpgrade] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airSuperSaverSeatRemaining] [int] NULL,
[airEconSaverSeatRemaining] [int] NULL,
[airFirstFlexSeatRemaining] [int] NULL,
[airCorporateSeatRemaining] [int] NULL,
[airEconFlexSeatRemaining] [int] NULL,
[airEconUpgradeSeatRemaining] [int] NULL,
[airSuperSaverFareReferenceKey] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airEconSaverFareReferenceKey] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airFirstFlexFareReferenceKey] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airCorporateFareReferenceKey] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airEconFlexFareReferenceKey] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airEconUpgradeFareReferenceKey] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airPriceClassSelected] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airSuperSaverTax] [float] NULL,
[airEconSaverTax] [float] NULL,
[airEconFlexTax] [float] NULL,
[airCorporateTax] [float] NULL,
[airEconUpgradetax] [float] NULL,
[airFirstFlexTax] [float] NULL,
[airSuperSaverFareBasisCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airEconSaverFareBasisCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airFirstFlexFareBasisCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airCorporateFareBasisCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airEconFlexFareBasisCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airEconUpgradeFareBasisCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[isBrandedFare] [bit] NULL,
[cabinClass] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fareType] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[isGeneratedBundle] [bit] NULL,
[ValidatingCarrier] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[contractCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airPriceBaseSenior] [float] NULL,
[airPriceTaxSenior] [float] NULL,
[airPriceBaseChildren] [float] NULL,
[airPriceTaxChildren] [float] NULL,
[airPriceBaseInfant] [float] NULL,
[airPriceTaxInfant] [float] NULL,
[airPriceBaseDisplay] [float] NULL,
[airPriceTaxDisplay] [float] NULL,
[airPriceBaseTotal] [float] NULL,
[airPriceTaxTotal] [float] NULL,
[airPriceBaseYouth] [float] NULL,
[airPriceTaxYouth] [float] NULL,
[airCurrencyCode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airResponseId] [bigint] NOT NULL,
[airPriceBaseInfantWithSeat] [float] NULL,
[airPriceTaxInfantWithSeat] [float] NULL,
[agentwareQueryID] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[agentwareItineraryID] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Points] [int] NULL,
[ticketDesignator] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[awardCode] [nvarchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ITAQueryId] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ITAItineraryId] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[isAvailable] [bit] NULL,
[isReturnFare] [bit] NULL,
CONSTRAINT [PK_AirResponse_1] PRIMARY KEY NONCLUSTERED  ([airResponseId])
)
WITH
(
MEMORY_OPTIMIZED = ON,
DURABILITY = SCHEMA_ONLY
)
GO
