CREATE TABLE [dbo].[TripHotelResponseHistory]
(
[TripHotelResponseKey] [int] NOT NULL,
[hotelResponseKey] [uniqueidentifier] NOT NULL,
[supplierHotelKey] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[tripKey] [int] NULL,
[tripGUIDKey] [uniqueidentifier] NULL,
[supplierId] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[minRate] [float] NOT NULL,
[minRateTax] [float] NOT NULL,
[hotelDailyPrice] [float] NOT NULL,
[hotelDescription] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[hotelRatePlanCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[hotelTotalPrice] [float] NULL,
[hotelPriceType] [int] NULL,
[hotelTaxRate] [float] NULL,
[rateDescription] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[guaranteeCode] [nchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SearchHotelPrice] [float] NOT NULL,
[searchHotelTax] [float] NULL,
[actualHotelPrice] [float] NULL,
[actualHotelTax] [float] NULL,
[checkInDate] [datetime] NULL,
[checkOutDate] [datetime] NULL,
[recordLocator] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[confirmationNumber] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CurrencyCodeKey] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PolicyReasonCodeID] [int] NULL,
[HotelPolicyKey] [int] NULL,
[PolicyResaonCode] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[isExpenseAdded] [bit] NULL,
[roomAmenities] [varchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cancellationPolicy] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[checkInInstruction] [varchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[hotelCheckInTime] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[hotelCheckOutTime] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[status] [int] NULL,
[isDeleted] [bit] NULL,
[vendorCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cityCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[preferenceOrder] [int] NULL,
[contractCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HotelPolicy] [varchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[yieldManagementValueKey] [int] NULL,
[SupplierType] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[perPersonDailyBaseCost] [float] NULL,
[perPersonDailyTotal] [float] NULL,
[hotelRoomTypeCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[creationDate] [datetime] NULL,
[salesTaxAndHotelOccupancyTax] [float] NULL,
[originalHotelTotalPrice] [float] NULL,
[isOnlineBooking] [bit] NULL,
[InvoiceNumber] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[roomDescriptionShort] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RPH] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsPromoTrue] [bit] NULL,
[PromoDescription] [varchar] (300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AverageBaseRate] [float] NULL,
[PromoId] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MarketplaceMarginPercent] [float] NULL,
[DepositAmount] [float] NULL,
[estimatedRefundAmount] [float] NULL,
[HotelId] [bigint] NULL
) ON [PRIMARY]
GO
