CREATE TABLE [dbo].[PreCheckInHotelBooked]
(
[UploadKey] [uniqueidentifier] NULL,
[PNR] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CName] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Chain] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SabreID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TouricoID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EANID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HotelName] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Nights] [nchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RoomType] [nchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Rate] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Currency] [nchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Total] [nchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Traveler] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CheckIn] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CheckOut] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CityName] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cancellation] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Phone] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Status] [bit] NULL CONSTRAINT [DF_PreCheckInHotelBooked_Status] DEFAULT ((0)),
[Source] [nchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TouricoNet] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TouricoCalaculationBarRate] [nchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TouricoCostBasisRate] [nchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RoomDescription] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RatePlanCode] [nchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RoomTypeCode] [nchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SourceCancellationPolicy] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EANBar] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreatedDate] [datetime] NULL,
[Savings] [float] NULL,
[Remarks] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SavingsTourico] [float] NULL,
[SavingsEAN] [float] NULL
) ON [PRIMARY]
GO
