CREATE TABLE [dbo].[TripCarResponseHistory]
(
[TripCarResponseKey] [int] NOT NULL,
[carResponseKey] [uniqueidentifier] NOT NULL,
[tripKey] [int] NULL,
[tripGUIDKey] [uniqueidentifier] NULL,
[carVendorKey] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[supplierId] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[carCategoryCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[carLocationCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[carLocationCategoryCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[minRate] [float] NOT NULL,
[minRateTax] [float] NOT NULL,
[DailyRate] [float] NULL,
[TotalChargeAmt] [float] NULL,
[NoOfDays] [int] NULL,
[SearchCarPrice] [float] NOT NULL,
[searchCarTax] [float] NULL,
[actualCarPrice] [float] NULL,
[actualCarTax] [float] NULL,
[pickUpDate] [datetime] NULL,
[dropOutDate] [datetime] NULL,
[recordLocator] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[confirmationNumber] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CurrencyCodeKey] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PolicyReasonCodeID] [int] NULL,
[CarPolicyKey] [int] NULL,
[PolicyResaonCode] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[isExpenseAdded] [bit] NULL,
[status] [int] NULL,
[isDeleted] [bit] NULL,
[contractCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[creationDate] [datetime] NULL,
[TripPassengerInfoKey] [int] NULL,
[rateTypeCode] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[carRules] [varchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OperationTimeStart] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OperationTimeEnd] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PickupLocationInfo] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[isOnlineBooking] [bit] NULL,
[InvoiceNumber] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MileageAllowance] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RPH] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PhoneNumber] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[carDropOffLocationCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[carDropOffLocationCategoryCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
