CREATE TABLE [dbo].[TripDetailsHistory]
(
[tripDetailsKey] [bigint] NOT NULL,
[tripKey] [bigint] NULL,
[tripSavedKey] [uniqueidentifier] NULL,
[userKey] [bigint] NULL,
[tripFrom] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tripTo] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tripStartDate] [datetime] NULL,
[tripEndMonth] [int] NULL,
[tripEndYear] [int] NULL,
[latestDealAirSavingsPerPerson] [float] NULL,
[latestDealHotelSavingsPerPerson] [float] NULL,
[latestDealCarSavingsPerPerson] [float] NULL,
[latestDealAirSavingsTotal] [float] NULL,
[latestDealHotelSavingsTotal] [float] NULL,
[latestDealCarSavingsTotal] [float] NULL,
[latestDealAirPricePerPerson] [float] NULL,
[latestDealHotelPricePerPerson] [float] NULL,
[latestDealCarPricePerPerson] [float] NULL,
[latestDealAirPriceTotal] [float] NULL,
[latestDealHotelPriceTotal] [float] NULL,
[latestDealCarPriceTotal] [float] NULL,
[AirRequestTypeName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AirCabin] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HotelRegionName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HotelRating] [float] NULL,
[HotelName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CarClass] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CarVendorCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[componentType] [int] NULL,
[fromCountryCode] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fromCountryName] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fromStateCode] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fromCityName] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[toCountryCode] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[toCountryName] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[toStateCode] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[toCityName] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tripEndDate] [datetime] NULL,
[HotelResponseKey] [uniqueidentifier] NULL,
[lastUpdatedDate] [datetime] NULL,
[originalPerPersonPriceAir] [float] NULL,
[originalTotalPriceAir] [float] NULL,
[originalPerPersonPriceCar] [float] NULL,
[originalTotalPriceCar] [float] NULL,
[originalPerPersonPriceHotel] [float] NULL,
[originalTotalPriceHotel] [float] NULL,
[originalPerPersonDailyTotalHotel] [float] NULL,
[dailyPriceHotel] [float] NULL,
[NoOfHotelRooms] [int] NULL,
[LatestHotelId] [int] NULL,
[LatestDealHotelPricePerPersonPerDay] [float] NULL,
[HotelNoOfDays] [int] NULL,
[LatestHotelRegionId] [int] NULL,
[LatestAirLineCode] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LatestAirlineName] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LatestHotelChainCode] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LatestCarVendorName] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CurrentHotelsComId] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CurrentTouricoId] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CurrentSabreHotelId] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NumberOfCurrentAirStops] [int] NULL,
[CrowdId] [int] NULL,
[CreatedDate] [datetime] NULL
) ON [PRIMARY]
GO
