CREATE TABLE [dbo].[M_AirSegments]
(
[airSegmentKey] [uniqueidentifier] NOT NULL,
[airResponseKey] [uniqueidentifier] NULL,
[airLegNumber] [int] NULL,
[airSegmentMarketingAirlineCode] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airSegmentOperatingAirlineCode] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airSegmentFlightNumber] [int] NULL,
[airSegmentDuration] [time] NULL,
[airSegmentEquipment] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airSegmentMiles] [int] NULL,
[airSegmentDepartureDate] [datetime] NULL,
[airSegmentArrivalDate] [datetime] NULL,
[airSegmentDepartureAirport] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airSegmentArrivalAirport] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airSegmentResBookDesigCode] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airSegmentDepartureOffset] [float] NULL,
[airSegmentArrivalOffset] [float] NULL,
[airSegmentSeatRemaining] [int] NULL,
[airSegmentMarriageGrp] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airFareBasisCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airFareReferenceKey] [varchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airSegmentOperatingFlightNumber] [int] NULL,
[airsegmentCabin] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[segmentOrder] [int] NULL,
[amadeusSNDIndicator] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airSegmentOperatingAirlineCompanyShortName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OriginalairsegmentCabin] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airSegmentId] [bigint] NOT NULL,
[airSuperSaverFareBasisCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airEconSaverFareBasisCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airFirstFlexFareBasisCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airCorporateFareBasisCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airEconFlexFareBasisCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airEconUpgradeFareBasisCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airSuperSaverFareReferenceKey] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airEconSaverFareReferenceKey] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airFirstFlexFareReferenceKey] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airCorporateFareReferenceKey] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airEconFlexFareReferenceKey] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airEconUpgradeFareReferenceKey] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airSegmentClassSuperSaver] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airSegmentClassEconSaver] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airSegmentClassFirstFlex] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airSegmentClassEconFlex] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airsegmentPricingKey] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airsegmentFareCategory] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airSegmentBrandName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airSegmentBrandID] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airSegmentBaggage] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airSegmentMealCode] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airSegmentStops] [int] NULL,
[ProgramCode] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[isReturnFare] [bit] NULL,
CONSTRAINT [PK_AirSegments_1] PRIMARY KEY NONCLUSTERED  ([airSegmentId])
)
WITH
(
MEMORY_OPTIMIZED = ON,
DURABILITY = SCHEMA_ONLY
)
GO
