CREATE TABLE [dbo].[TripAirResponseHistory]
(
[tripAirResponseKey] [int] NOT NULL,
[airResponseKey] [uniqueidentifier] NOT NULL,
[tripKey] [int] NULL,
[tripGUIDKey] [uniqueidentifier] NULL,
[searchAirPrice] [float] NOT NULL,
[searchAirTax] [float] NULL,
[searchAirPriceBreakupKey] [int] NULL,
[actualAirPrice] [float] NULL,
[actualAirTax] [float] NULL,
[actualAirPriceBreakupKey] [int] NULL,
[CurrencyCodeKey] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PolicyReasonCodeID] [int] NULL,
[PolicyKey] [int] NULL,
[PolicyResaonCode] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[isExpenseAdded] [bit] NULL,
[repricedAirPrice] [float] NULL,
[repricedAirTax] [float] NULL,
[repricedAirPriceBreakupKey] [int] NULL,
[bookingCharges] [float] NULL,
[appliedDiscount] [float] NULL,
[ValidatingCarrier] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[discountedBaseFare] [float] NULL,
[discountedTax] [float] NULL,
[status] [int] NULL,
[isDeleted] [bit] NULL,
[publishedAirPriceBreakupKey] [int] NULL,
[isOnlineBooking] [bit] NULL,
[isSplit] [bit] NULL,
[agentWareQueryID] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[agentwareItineraryID] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
