CREATE TABLE [dbo].[TripPromotionHistory]
(
[PromoId] [int] NOT NULL,
[PromoCampaignName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PublicCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PromoCampaignType] [int] NULL,
[DiscountRate] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UsageRestriction] [int] NULL,
[OfferMatchType] [int] NULL,
[HotelVenorMatch] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HotelChainMatch] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HotelGroupMatch] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CitySpecificMatch] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SpecificAirportCodeMatch] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PurchaseStart] [datetime] NULL,
[PuchaseEnd] [datetime] NULL,
[TravelDateStart] [datetime] NULL,
[TravelDateEnd] [datetime] NULL,
[MinimumNightStayRequirement] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MinimumSpendRequirement] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PromoCodeApplied] [int] NULL,
[IsTravelAirCarHotelEligible] [bit] NULL,
[IsAirHoteEligible] [bit] NULL,
[IsHotelOnlyEligible] [bit] NULL,
[IsAllActivtyEligible] [bit] NULL,
[IsTravelToMexicoEligible] [bit] NULL,
[IsTravelToCaribbeanEligible] [bit] NULL,
[IsTravelToEuropeEligible] [bit] NULL,
[IsTravelToSouthAmericaEligible] [bit] NULL,
[CreateDate] [datetime] NULL,
[ModifiedDate] [datetime] NULL,
[UserKey] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CitySpecificMatchKey] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TripGuidKey] [uniqueidentifier] NULL,
[PromotionDiscount] [float] NULL
) ON [PRIMARY]
GO
