CREATE TABLE [dbo].[tblvw_TripCarResponseDetails]
(
[recordLocator] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[carResponseKey] [uniqueidentifier] NOT NULL,
[confirmationNumber] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[carVendorKey] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[supplierId] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[carCategoryCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[carLocationCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[carLocationCategoryCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PerDayRate] [float] NOT NULL,
[searchCarTax] [float] NULL,
[actualCarPrice] [float] NULL,
[actualCarTax] [float] NULL,
[SearchCarPrice] [float] NOT NULL,
[VehicleName] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pickupLocationName] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pickupLocationAddress] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pickupLatitude] [float] NULL,
[pickupLongitude] [float] NULL,
[pickupZipCode] [nvarchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dropoffLatitude] [float] NULL,
[dropoffLongitude] [float] NULL,
[dropoffZipCode] [nvarchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dropoffLocationAddress] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dropoffLocationName] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PickUpdate] [datetime] NULL,
[dropOutDate] [datetime] NULL,
[SippCodeDescription] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SippCodeTransmission] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SippCodeAC] [int] NULL,
[CarCompanyName] [nvarchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SippCodeClass] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dropoffCity] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dropoffState] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dropoffCountry] [nvarchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pickupCity] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pickupState] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pickupCountry] [nvarchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[minRateTax] [float] NOT NULL,
[TotalChargeAmt] [float] NULL,
[minRate] [float] NOT NULL,
[passenger] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[baggage] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[isExpenseAdded] [bit] NULL,
[NoOfDays] [int] NULL,
[tripGUIDKey] [uniqueidentifier] NULL,
[contractCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[carRules] [varchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tripKey] [int] NULL,
[rateTypeCode] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OperationTimeStart] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OperationTimeEnd] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PickupLocationInfo] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InvoiceNumber] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MileageAllowance] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RPH] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CurrencyCodeKey] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[imageName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PhoneNumber] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[carDropOffLocationCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[carDropOffLocationCategoryCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
