CREATE TABLE [dbo].[FinanceDetails]
(
[tripKey] [int] NULL,
[IssueDate] [datetime] NULL,
[CreationDate] [datetime] NULL,
[PassengerName] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AirVendor] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AirGDS] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GDSHotelId] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HotelName] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HotelGDS] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CarVendor] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CarGDS] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TotalFare] [float] NULL,
[BaseFare] [float] NULL,
[Commission] [float] NULL,
[AirDepartureCity] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AirArrivalCity] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AirDepartureDate] [datetime] NULL,
[AirReturnDate] [datetime] NULL,
[HotelCity] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CarPickupCity] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CarDropoffCity] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[recordLocator] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AirTicketNumber] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AirItineraryNumber] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HotelTicketNumber] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HotelItineraryNumber] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CarTicketNumber] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CarItineraryNumber] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TravelType] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Udid] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TripRequestKey] [int] NULL,
[TripPurchaseKey] [uniqueidentifier] NULL
) ON [PRIMARY]
GO
