CREATE TABLE [dbo].[Trip_History]
(
[TripHistoryKey] [uniqueidentifier] NOT NULL,
[tripKey] [int] NULL,
[tripName] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[userKey] [int] NULL,
[recordLocator] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[startDate] [datetime] NULL,
[endDate] [datetime] NULL,
[tripStatusKey] [int] NOT NULL,
[tripSavedKey] [uniqueidentifier] NULL,
[tripPurchasedKey] [uniqueidentifier] NULL,
[agencyKey] [int] NULL,
[tripComponentType] [smallint] NULL,
[tripRequestKey] [int] NULL,
[CreatedDate] [datetime] NULL,
[meetingCodeKey] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[deniedReason] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[siteKey] [int] NULL,
[isBid] [bit] NULL,
[isOnlineBooking] [bit] NULL,
[tripAdultsCount] [int] NULL,
[tripSeniorsCount] [int] NULL,
[tripChildCount] [int] NULL,
[tripInfantCount] [int] NULL,
[tripYouthCount] [int] NULL,
[noOfTotalTraveler] [int] NULL,
[noOfRooms] [int] NULL,
[noOfCars] [int] NULL,
[PurchaseComponentType] [int] NULL,
[tripTotalBaseCost] [float] NULL,
[tripTotalTaxCost] [float] NULL,
[ModifiedDateTime] [datetime] NULL,
[IsWatching] [bit] NULL,
[tripOriginalTotalBaseCost] [float] NULL,
[tripOriginalTotalTaxCost] [float] NULL,
[tripInfantWithSeatCount] [int] NULL,
[passiveRecordLocator] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[isAudit] [bit] NULL,
[bookingCharges] [float] NULL,
[isUserCreatedSavedTrip] [bit] NULL,
[ISSUEDATE] [datetime] NULL,
[privacyType] [int] NULL,
[HomeAirport] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DestinationSmallImageURL] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FollowersCount] [int] NULL,
[tripCreationPath] [int] NULL,
[CrowdCount] [bigint] NULL,
[TrackingLogID] [int] NULL,
[bookingFeeARC] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsHotelCrowdSavings] [bit] NULL,
[SabreCreationDate] [datetime] NULL,
[promoId] [int] NULL,
[InsertDate] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Trip_History] ADD CONSTRAINT [pk_Trip_HistoryTripKey] PRIMARY KEY CLUSTERED  ([TripHistoryKey]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
