CREATE TABLE [dbo].[CachingTMU]
(
[tripKey] [int] NULL,
[tripsavedKey] [uniqueidentifier] NULL,
[triprequestkey] [int] NULL,
[userKey] [int] NULL,
[tripstartdate] [datetime] NULL,
[tripenddate] [datetime] NULL,
[tripfrom] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tripTo] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tripComponentType] [int] NULL,
[tripComponents] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[rankRating] [float] NULL,
[tripAirsavings] [float] NULL,
[tripcarsavings] [float] NULL,
[triphotelsavings] [float] NULL,
[isOffer] [bit] NULL,
[OfferImageURL] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LinktoPage] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[currentTotalPrice] [float] NULL,
[originalTotalPrice] [float] NULL,
[UserName] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FacebookUserUrl] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WatchersCount] [int] NULL,
[LikeCount] [int] NULL,
[IsWatcher] [bit] NULL CONSTRAINT [DF__tmp_ms_xx__IsWat__0A295FE6] DEFAULT ((0)),
[BookersCount] [int] NULL CONSTRAINT [DF__tmp_ms_xx__Booke__0B1D841F] DEFAULT ((0)),
[TripPurchaseKey] [uniqueidentifier] NULL,
[FastestTrending] [float] NULL,
[TotalSavings] [float] NULL,
[Rating] [float] NULL,
[AirSegmentCabin] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CarClass] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AirRequestTypeName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NoOfStops] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HotelRegionName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TripScoring] [float] NULL,
[DestinationImageURL] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SavingsRanking] [float] NULL CONSTRAINT [DF__tmp_ms_xx__Savin__0C11A858] DEFAULT ((0)),
[Recency] [float] NULL CONSTRAINT [DF__tmp_ms_xx__Recen__0D05CC91] DEFAULT ((0)),
[RecencyRanking] [float] NULL CONSTRAINT [DF__tmp_ms_xx__Recen__0DF9F0CA] DEFAULT ((0)),
[Proximity] [int] NULL CONSTRAINT [DF__tmp_ms_xx__Proxi__0EEE1503] DEFAULT ((0)),
[ProximityRanking] [float] NULL CONSTRAINT [DF__tmp_ms_xx__Proxi__0FE2393C] DEFAULT ((0)),
[SocialRanking] [float] NULL CONSTRAINT [DF__tmp_ms_xx__Socia__10D65D75] DEFAULT ((0)),
[ComponentRanking] [float] NULL CONSTRAINT [DF__tmp_ms_xx__Compo__11CA81AE] DEFAULT ((0)),
[FromCity] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FromState] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FromCountry] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ToCity] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ToState] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ToCountry] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tripPurchasedKey] [uniqueidentifier] NULL,
[tripStatusKey] [int] NULL CONSTRAINT [DF__tmp_ms_xx__tripS__12BEA5E7] DEFAULT ((0)),
[IsMyTrip] [bit] NULL CONSTRAINT [DF__tmp_ms_xx__IsMyT__13B2CA20] DEFAULT ((0)),
[LatestDealAirPriceTotal] [float] NULL CONSTRAINT [DF__tmp_ms_xx__Lates__14A6EE59] DEFAULT ((0)),
[LatestDealHotelPriceTotal] [float] NULL CONSTRAINT [DF__tmp_ms_xx__Lates__159B1292] DEFAULT ((0)),
[LatestDealCarPriceTotal] [float] NULL CONSTRAINT [DF__tmp_ms_xx__Lates__168F36CB] DEFAULT ((0)),
[LatestDealAirPricePerPerson] [float] NULL CONSTRAINT [DF__tmp_ms_xx__Lates__17835B04] DEFAULT ((0)),
[LatestDealHotelPricePerPerson] [float] NULL CONSTRAINT [DF__tmp_ms_xx__Lates__18777F3D] DEFAULT ((0)),
[LatestDealCarPricePerPerson] [float] NULL CONSTRAINT [DF__tmp_ms_xx__Lates__196BA376] DEFAULT ((0)),
[IsBackFillData] [bit] NULL CONSTRAINT [DF__tmp_ms_xx__IsBac__1A5FC7AF] DEFAULT ((0)),
[IsZeroPriceAvailable] [bit] NULL CONSTRAINT [DF__tmp_ms_xx__IsZer__1B53EBE8] DEFAULT ((0)),
[LatestAirLineCode] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LatestAirlineName] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LatestHotelChainCode] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HotelName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CarVendorCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LatestCarVendorName] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CurrentHotelsComId] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LatestDealHotelPricePerPersonPerDay] [float] NULL CONSTRAINT [DF__tmp_ms_xx__Lates__1C481021] DEFAULT ((0)),
[DateRanking] [float] NULL CONSTRAINT [DF__tmp_ms_xx__DateR__1D3C345A] DEFAULT ((0)),
[NumberOfCurrentAirStops] [int] NULL CONSTRAINT [DF__tmp_ms_xx__Numbe__1E305893] DEFAULT ((0)),
[ExactCityMatchRanking] [float] NULL CONSTRAINT [DF__tmp_ms_xx__Exact__1F247CCC] DEFAULT ((0)),
[LatestHotelRegionId] [int] NULL CONSTRAINT [DF__tmp_ms_xx__Lates__2018A105] DEFAULT ((0)),
[CrowdId] [bigint] NULL,
[LatestDealAirSavingsTotal] [float] NULL CONSTRAINT [DF__tmp_ms_xx__Lates__210CC53E] DEFAULT ((0)),
[LatestDealCarSavingsTotal] [float] NULL CONSTRAINT [DF__tmp_ms_xx__Lates__2200E977] DEFAULT ((0)),
[LatestDealHotelSavingsTotal] [float] NULL CONSTRAINT [DF__tmp_ms_xx__Lates__22F50DB0] DEFAULT ((0)),
[LatestDealAirSavingsPerPerson] [float] NULL CONSTRAINT [DF__tmp_ms_xx__Lates__23E931E9] DEFAULT ((0)),
[LatestDealCarSavingsPerPerson] [float] NULL CONSTRAINT [DF__tmp_ms_xx__Lates__24DD5622] DEFAULT ((0)),
[LatestDealHotelSavingsPerPerson] [float] NULL CONSTRAINT [DF__tmp_ms_xx__Lates__25D17A5B] DEFAULT ((0)),
[IsEventAvailable] [bit] NULL CONSTRAINT [DF__tmp_ms_xx__IsEve__26C59E94] DEFAULT ((0)),
[EventKey] [bigint] NULL CONSTRAINT [DF__tmp_ms_xx__Event__27B9C2CD] DEFAULT ((0)),
[TotalTripSavings] [float] NULL CONSTRAINT [DF__tmp_ms_xx__Total__28ADE706] DEFAULT ((0)),
[TotalTripCount] [int] NULL CONSTRAINT [DF__tmp_ms_xx__Total__29A20B3F] DEFAULT ((0)),
[AttendeeStatuskey] [int] NULL CONSTRAINT [DF__tmp_ms_xx__Atten__2A962F78] DEFAULT ((0)),
[TripPrivacyType] [int] NULL,
[MinFollowedTotal] [int] NULL CONSTRAINT [DF__tmp_ms_xx__MinFo__2B8A53B1] DEFAULT ((0)),
[MaxFollowedTotal] [int] NULL CONSTRAINT [DF__tmp_ms_xx__MaxFo__2C7E77EA] DEFAULT ((0)),
[MinSavingsTotal] [bigint] NULL CONSTRAINT [DF__tmp_ms_xx__MinSa__2D729C23] DEFAULT ((0)),
[MaxSavingsTotal] [bigint] NULL CONSTRAINT [DF__tmp_ms_xx__MaxSa__2E66C05C] DEFAULT ((0)),
[MinBestPriceTotal] [bigint] NULL CONSTRAINT [DF__tmp_ms_xx__MinBe__2F5AE495] DEFAULT ((0)),
[MaxBestPriceTotal] [bigint] NULL CONSTRAINT [DF__tmp_ms_xx__MaxBe__304F08CE] DEFAULT ((0)),
[HotelNoOfNights] [int] NULL CONSTRAINT [DF__tmp_ms_xx__Hotel__31432D07] DEFAULT ((1)),
[InCrowd] [int] NULL CONSTRAINT [DF__tmp_ms_xx__InCro__32375140] DEFAULT ((0)),
[HotelId] [bigint] NULL CONSTRAINT [DF__tmp_ms_xx__Hotel__332B7579] DEFAULT ((0))
) ON [PRIMARY]
GO
