CREATE TABLE [dbo].[AirResponseResultSet]
(
[airSegmentKey] [uniqueidentifier] NULL,
[airResponseKey] [uniqueidentifier] NULL,
[airLegNumber] [int] NULL,
[airSegmentMarketingAirlineCode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airSegmentFlightNumber] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airSegmentDuration] [time] NULL,
[airSegmentEquipment] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airSegmentMiles] [int] NULL,
[airSegmentDepartureDate] [datetime] NULL,
[airSegmentArrivalDate] [datetime] NULL,
[airSegmentDepartureAirport] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airSegmentArrivalAirport] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airPrice] [float] NULL,
[airPriceTax] [float] NULL,
[airPriceBaseSenior] [float] NULL,
[airPriceTaxSenior] [float] NULL,
[airPriceBaseChildren] [float] NULL,
[airPriceTaxChildren] [float] NULL,
[airPriceBaseInfant] [float] NULL,
[airPriceTaxInfant] [float] NULL,
[airPriceBaseYouth] [float] NULL,
[airPriceTaxYouth] [float] NULL,
[AirPriceBaseTotal] [float] NULL,
[AirPriceTaxTotal] [float] NULL,
[airPriceBaseDisplay] [float] NULL,
[airPriceTaxDisplay] [float] NULL,
[airRequestKey] [int] NULL,
[gdsSourceKey] [int] NULL,
[MarketingAirlineName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NoOfSTOPs] [int] NULL,
[actualTakeOffDateForLeg] [datetime] NULL,
[actualLandingDateForLeg] [datetime] NULL,
[airSegmentOperatingAirlineCode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airSegmentResBookDesigCode] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[noofAirlines] [int] NULL,
[airlineName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airsegmentDepartureOffset] [float] NULL,
[airSegmentArrivalOffset] [float] NULL,
[airSegmentSeatRemaining] [int] NULL,
[priceClassCommentsSuperSaver] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[priceClassCommentsEconSaver] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[priceClassCommentsFirstFlex] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[priceClassCommentsCorporate] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[priceClassCommentsEconFlex] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[priceClassCommentsEconUpgrade] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airSuperSaverPrice] [float] NULL,
[airEconSaverPrice] [float] NULL,
[airFirstFlexPrice] [float] NULL,
[airCorporatePrice] [float] NULL,
[airEconFlexPrice] [float] NULL,
[airEconUpgradePrice] [float] NULL,
[airClassSuperSaver] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airClassEconSaver] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airClassFirstFlex] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airClassCorporate] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airClassEconFlex] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airClassEconUpgrade] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airSuperSaverSeatRemaining] [int] NULL,
[airEconSaverSeatRemaining] [int] NULL,
[airFirstFlexSeatRemaining] [int] NULL,
[airCorporateSeatRemaining] [int] NULL,
[airEconFlexSeatRemaining] [int] NULL,
[airEconUpgradeSeatRemaining] [int] NULL,
[airSuperSaverFareReferenceKey] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airEconSaverFareReferenceKey] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airFirstFlexFareReferenceKey] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airCorporateFareReferenceKey] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airEconFlexFareReferenceKey] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airEconUpgradeFareReferenceKey] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[airPriceClassSELECTed] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[otherLegPrice] [float] NULL,
[isRefundable] [bit] NULL,
[isBrandedFare] [bit] NULL,
[cabinClass] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fareType] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[segmentOrder] [int] NULL,
[airsegmentCabin] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[totalCost] [float] NULL,
[airSegmentOperatingFlightNumber] [int] NULL,
[otherlegtax] [float] NULL,
[airSegmentOperatingAirlineCompanyShortName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[otherlegAirlines] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[noOfOtherlegairlines] [int] NULL,
[airRowNum] [int] NOT NULL IDENTITY(1, 1),
[legDuration] [int] NULL,
[legConnections] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[actualNoOFStops] [int] NULL
) ON [PRIMARY]
GO
