CREATE TABLE [dbo].[HotelResponseDetail]
(
[hotelResponseDetailKey] [uniqueidentifier] NOT NULL,
[hotelResponseKey] [uniqueidentifier] NOT NULL,
[hotelDailyPrice] [float] NOT NULL,
[hotelDescription] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[supplierId] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[hotelRatePlanCode] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[hotelRoomTypeCode] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[hotelTotalPrice] [float] NULL,
[hotelPriceType] [int] NULL,
[hotelTaxRate] [float] NULL,
[rateDescription] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[guaranteeCode] [nchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CancellationPolicy] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[hotelsComSupplierType] [nchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[roomDescriptionShort] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[roomDescription] [varchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[roomAmenities] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[isNonRefundable] [bit] NULL,
[supplierHotelKey] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[originalHotelDailyPrice] [float] NULL,
[originalHotelTotalPrice] [float] NULL,
[yieldManagementValueKey] [int] NULL,
[originalHotelTaxRate] [float] NULL,
[hotelTaxPercentage] [float] NULL,
[salesTaxAndHotelOccupancyTax] [float] NULL,
[marketPlacePreferenceOrder] [int] NULL CONSTRAINT [DF__HotelResp__marke__7D446614] DEFAULT ((99)),
[depositAmount] [float] NULL,
[valueAdds] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[beforeCancellationDate] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[resortFee] [varchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsPromoTrue] [bit] NULL,
[PromoDescription] [varchar] (300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AverageBaseRate] [float] NULL,
[PromoId] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[touricoCalculationBarRate] [float] NULL,
[touricoNetRate] [float] NULL,
[displayPrice] [float] NULL,
[numberOfNights] [int] NULL,
[crowdPrice] [float] NULL,
[MarketplaceMarginPercent] [float] NULL,
[TouricoTaxRate] [float] NULL,
[roomImages] [varchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[contractCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[nightlyRates] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NoofRooms] [int] NULL CONSTRAINT [DF__HotelResp__NoofR__054F9C30] DEFAULT ((0)),
[IsGovtRate] [bit] NULL,
[IsCompanyContractApplied] [bit] NULL,
[rateKey] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[roomPolicy] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[atMerchant] [bit] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[HotelResponseDetail] ADD CONSTRAINT [PK_HotelResponseDetail] PRIMARY KEY CLUSTERED  ([hotelResponseDetailKey]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [Idx_hotelResponseKey] ON [dbo].[HotelResponseDetail] ([hotelResponseKey]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
